webapp/src/components/TokenTransfer/TokenTransfer.js
- Add scroll for token transfer modal
- make run
- go to `http://localhost:3000`
- login as lifebank
- go to profile page
- click Transfer option
=> chore: add scroll for token transfer modal

webapp/src/routes/Donation/DonationPage.js, webapp/src/routes/Help/Help.js
=> switch message donation page

hapi/src/routes/signup/signup.handler.js, hapi/src/utils/lifebankcode.js, wallet/Dockerfile, webapp/Dockerfile, webapp/public/index.html, webapp/src/components/LoginModal/Login.js, webapp/src/components/MapShowLocations/index.js, webapp/src/components/Schedule/Schedule.js, webapp/src/context/user.context.js, webapp/src/routes/Signup/Signup.js
- If you want a full detailed description, just go to the codefactor [project](https://www.codefactor.io/repository/github/eoscostarica/lifebank).
- Closes #189 #192 #190 #194 #195 #196 #197 #198 #199
=>  Bugs found by codefactor fixed

wallet/Dockerfile
=> fix(wallet): update eosio package version

webapp/src/gql/offer.gql.js, webapp/src/routes/OffersManagement/GenericOfferFormComponent.js, webapp/src/routes/OffersManagement/OffersManagement.js
Now, edit functionality has been added to previous included feats.
1. Clone this branch
1. Execute `make install`
1. Execute `make run`
1. Go to `localhost:3000` and see the changes
Codefactor suggests some possible code improvements. But that can't be fixed, because it's the way that DB expects data to be named﻿
=> Edit Functionality

webapp/src/routes/OffersManagement/OffersManagement.js
Form dialog wasn't able to open due to incorrect provided validation. This validations is now included.﻿
- closes #236
=> fix: allow open dialog to add new offer. Add proper validation

webapp/src/components/MapShowOneLocation/index.js, webapp/src/components/Schedule/Schedule.js, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/Profile/ProfilePageLifebank.js
#215 
- Add map component to edit profile lifebank
- Modify MapShowOneLocation component to show markerType
- Run make run
- go to localhost:3000
=> content(profilePageLifebank): add map component to edit profile lifebank

hasura/metadata/tables.yaml, webapp/src/containers/SideBar.js, webapp/src/gql/offer.gql.js, webapp/src/routes/OfferPage/OfferPage.js, webapp/src/routes/OfferPage/index.js, webapp/src/routes/Offers/Offers.js, webapp/src/routes/Offers/index.js, webapp/src/routes/index.js
#188 
- create a page when the donor can see the sponsors' offers
- create filters for offers searches
- create a page when the donor can see a specific offer
- make run
- login as donor
- go to available offers section
=> feat: offer pages 

webapp/src/gql/offer.gql.js, webapp/src/routes/OffersManagement/GenericOfferFormComponent.js, webapp/src/routes/OffersManagement/OffersManagement.js
It's necessary to improve usability in sponsor offers management
- Improve sponsor offers management usability
- Minimal bug fixes
- Execute `make install` (if you don't have the dependencies)
- Execute `make run`
- Go to `localhost:3000` and see the new changes
=> fix: improve offer management usability

hasura/migrations/1590526643953_create_table_public_user/up.sql, hasura/migrations/1601327631743_create_table_public_verificate_email/up.sql, hasura/migrations/1601330035486_delete_fk_public_verificate_email_verificate_email_email_fkey/down.sql, hasura/migrations/1601330035486_delete_fk_public_verificate_email_verificate_email_email_fkey/up.sql, hasura/migrations/1601330204205_delete_fk_public_verificate_email_verificate_email_email_fkey1/down.sql, hasura/migrations/1601330204205_delete_fk_public_verificate_email_verificate_email_email_fkey1/up.sql
- fix hasura conflicts 
- remove FK in the verification email table
- remove migrations related verification email FK's
How should this be tested?
- Run make run
- go to localhost:3000
=> fix: hasura conflicts

hapi/src/api/account.api.js, hapi/src/utils/mail.js, webapp/src/components/LoginModal/Login.js, webapp/src/gql/account.gql.js, webapp/src/routes/Signup/Signup.js, webapp/src/routes/Signup/SignupDonor.js, webapp/src/routes/Signup/SignupSponsor/SimpleRegisterForm.js
- include confirm password field
- add sending email verification
- allow login with account or username
- fix email subject
- go to http://localhost:3000/signup
- register as donor
=> donor register

webapp/src/gql/offer.gql.js, webapp/src/routes/OffersManagement/GenericOfferFormComponent.js, webapp/src/routes/OffersManagement/OfferDetails.js
This PR close edit offer bug isse
- fix edit offer bug
- Execute `make run`
- Go to `localhost:3000`
- Login as sponsor
- Go to offer management and edit one offer
closes #271
=> fix: fix edit offer bug

webapp/src/components/LoginModal/Login.js
- solve problem with Facebook and Google login
- login with Facebook or Google
=> fix: login with facebook or google auth

webapp/src/components/LanguageSelector/LanguageSelector.js, webapp/src/components/Notification/Notification.js, webapp/src/containers/Main.js, webapp/src/containers/TopBar.js
- fix item colors in the navbar
- add shadow to the navbar
=> update navbar design 

webapp/src/routes/Home/Home.js, webapp/src/routes/Home/ShowLifebanks.js, webapp/src/routes/Home/ShowOffers.js, webapp/src/routes/Home/ShowSponsors.js
- make cards scroll horizontal
=> Slide cards

webapp/src/components/MapShowLocations/index.js
#250 
- fit filter map dialog on small screens
- browse with a map
- open filter options on a small screen
=> fix: fit filter dialog on small screens

webapp/src/components/FilterHome/FilterHome.js, webapp/src/components/FilterHome/index.js, webapp/src/components/MapModal/MapModal.js, webapp/src/routes/Home/Home.js, webapp/src/routes/Home/HomeDesktop.js, webapp/src/routes/Home/HomeMobile.js
What does this PR do?
- solve problems that affect user experience in front-page
=> front-page UX problems

hapi/src/api/account.api.js, webapp/src/components/Logo/Logo.js, webapp/src/routes/EditProfile/EditProfile.js, webapp/src/routes/EditProfile/EditProfileSponsor.js, webapp/src/routes/Profile/ProfilePageSponsor.js, webapp/src/routes/Signup/SignupSponsor/SimpleRegisterForm.js
Fix bug when trying to complete sponsor profile
- Fix complete sponsor functionality bug
- Minimal code improvements
- Execute `make install`
- Execute `make run`
- Go to `localhost:3000` and either login o register yourself as a sponsor
- Go to profile section and update it
closes #267
=> fix: fix complete sponsor info functionality

.gitignore, contracts/scripts/lifebank.sh
This PR provides the initial node initialization script
- Navigate to `contracts/secrets`
- Execute `lifebank.sh`
=> Lifebank node initialization script

webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
#302
Fix margin-top on CredentialsRecovery Component
I also add the property:
cursor:pointer
go to http://localhost:3000
open nav
=> style(frontend): Fix margin on CredentialsRecovery Component

webapp/src/routes/Home/HomeDesktop.js
Fix padding by targeting the nested component in the SearchBar Root component for Desktop screen size.
#299 
go to http://localhost:3000
=> style(frontend): fix padding on seachbar for desktop

webapp/src/components/VideoSection/VideoSection.js
Video style response to screen sizes is implemented with React Hooks and MaterialUI
Issue: #321
=> feature(frontend): Improve video response to screen sizes

webapp/src/routes/TermsOfUse/TermsOfUse.js
#320 
Fix margin and response to small screen sizes on /termsofuse Tab component
go to http://localhost:3000/terms-of-use
=> style(frontend): Fix margin and response to small screen sizes 

webapp/src/routes/Home/ShowLifebanks.js, webapp/src/routes/Home/ShowOffers.js, webapp/src/routes/Home/ShowSponsors.js
- add logo image to avatar in lifebanks and sponsor cards
- add offer image to avatar 
- fix problems with sponsor cards
=> feat: add logo to avatar

webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
#315
Makes the Credentials Recovery component accesible with the tab keyword.
go to http://localhost:3000
=> feature(frontend): Credentials Recovery is accesible through tab key

webapp/src/App.js, webapp/src/containers/Main.js, webapp/src/containers/SideBar.js
#316 
SideBar navigational component swipes out after item selection. This improves web navigation through tab keyword. 
go to http://localhost:3000
Select any item on the side bar.
=> feature(frontend):sidebar navigation swipe out after item selection

hapi/src/api/account.api.js, webapp/src/App.js, webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js, webapp/src/gql/account.gql.js, webapp/src/routes/EditProfile/EditProfileSponsor.js, webapp/src/routes/Profile/ProfilePageSponsor.js
This PR provides the fix for social media links error in local business schema component
- `make install`
- `make run`
- Go to `localhost:3000` and check if the console displays any error
- closes #349
=> fix: fix sameAs attr in local business schema

contracts/scripts/lifebank.sh
This pull request updates the bootstrap script (lifebank.sh)
=> chore: update lifebank script

webapp/package.json, webapp/src/components/SearchComponent/SeachComponent.js, webapp/src/components/SearchComponent/index.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/Home/Home.js, webapp/src/routes/Home/HomeDesktop.js, webapp/src/routes/Home/HomeMobile.js, webapp/src/routes/Home/ShowLifebanks.js, webapp/src/routes/Home/ShowOffers.js, webapp/src/routes/Home/ShowSponsors.js, webapp/yarn.lock
closes #352 
- enable search for offers, lifebanks or sponsors
- add voice search
- find an offer, lifebank or sponsor using search component
=> feat: search component

webapp/src/components/Nearby/Nerby.js, webapp/src/components/Nearby/index.js, webapp/src/gql/location.gql.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/InfoPage/InfoPage.js
closes #370
- Redesign info pages
- Fix problems in the mobile version
- open info pages from lifebank or sponsor
=> feat: info pages redesign

hapi/src/api/account.api.js, hapi/src/api/pre-register.api.js, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/EditProfile/EditProfileDonor.js, webapp/src/routes/Profile/ProfilePageDonor.js, webapp/src/routes/Profile/ProfilePageLifebank.js
#351 
- add username atribute in location.state
- Run make run
- Go to edit profile donor section
=> fix bug: edit profile donor broke

webapp/src/language/en.json
Minor changes in the English version.
=> Update 2 en.json

webapp/src/language/en.json
Minor changes in the English version.
=> Update 1 en.json

hapi/src/api/account.api.js, hapi/src/utils/jwt.js, hapi/src/utils/lifebankcode.js
- fix bug in consent lifebank
- add more time to expired basic token
- Run make run
- Register and consent lifebank
=> fix bug in consent lifebank

hapi/src/api/sponsor.api.js, webapp/src/components/Carousel/Carousel.js, webapp/src/components/Logo/Logo.js, webapp/src/components/Nearby/Nerby.js, webapp/src/components/OfferView/OfferView.js, webapp/src/routes/Home/ShowLifebanks.js, webapp/src/routes/Home/ShowOffers.js, webapp/src/routes/Home/ShowSponsors.js, webapp/src/routes/InfoPage/InfoPage.js, webapp/src/routes/Profile/ProfilePageLifebank.js
This PR provides minimal changes to allow image caching. We are using images.weserv.nl service to allow image caching in our project for free.
- make run
- Go to `locahost:3000` and inspect the image you want to analyze
=> feat: allow image caching

webapp/src/App.js, webapp/src/components/SplashIntro/SplashIntro.js
This PR provides a refactorization to Splash intro component, in order to allow structured data validation.
- Remove duplicated code
- Allow fullscreen modal in mobile
- Cookie validation is now in mobile component
- #411
=> fix splash intro loading

webapp/package.json, webapp/src/sitemap.xml, webapp/yarn.lock
This PR adds sitemap file to enhance SEO ranking
closes #416
=> feat: add sitemap

webapp/debug.log, webapp/src/components/CredentialsRecovery/CredentialsRecovery.js, webapp/src/components/LoginModal/Login.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/EditProfile/EditProfileSponsor.js, webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
closes #413
- Add in Login
- Add in credential component
- Add function in add image and add telephone in edit profile sponsor
- Add function in add image and add telephone in edit profile lifebankc
- Run make run
- Go to credential component, login, edit profile sponsor, edit profile lifebank
=> Excecute acctions with enter key

webapp/src/components/ShowElements/ShowLifebanksMobile.js, webapp/src/components/ShowElements/ShowSponsorsMobile.js
- solve minimum warnings
How this should be tested?
=> solve warnings

webapp/src/components/DonationsDashboard/DonationsDashboard.js
-  add feature to select camera
- scan qr code
=> feat: select camera when scanning qr

webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js, webapp/src/components/MedicalClinicStructuredData/MedicalClinicStructuredData.js, webapp/src/routes/Home/Home.js
Google warned some errors regarding to structured data. Specifically the image field was missing. Other minor tweaks have been applied.
=> wip: fix structured data

webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js, webapp/src/routes/Home/Home.js
This PR provides a fix for missing parse validation when photos were sent to LocalBusiness & MedicalClinic schemas.
- Fix missing parse validation
closes #431
=> fix: missing parse in el.photos

webapp/src/components/LoginModal/Login.js, webapp/src/components/Schedule/Schedule.js
closes #430
- Update login modal to full screen in mobile version
- Run make run
- Go to localhost: 3000
- Go to login section
=> Login modal, change to full screen in mobile version

webapp/src/components/Schedule/Schedule.js, webapp/src/containers/TopBar.js
closes #290 
- Fix bug to logout in profile section
- Change stile to add button in schedule component
- Run make run
- Go to profile page and logout in this section.
- Go to schedule component and view add button.
=> Broke logout in profile section

webapp/src/components/ShowElements/ShowLifebanksDesktop.js, webapp/src/components/ShowElements/ShowLifebanksMobile.js, webapp/src/components/ShowElements/ShowOffersDesktop.js, webapp/src/components/ShowElements/ShowOffersMobile.js, webapp/src/components/ShowElements/ShowSponsorsDesktop.js, webapp/src/components/ShowElements/ShowSponsorsMobile.js
closes #379
- Fix scroll vertical in cards, this broke design
- Fix view list when show scroll in mobile version
- Run make run
- Go to home page and create sponsors, lifebanks or offerts until show scroll, and review that is ok
=> Broke home page desing movile and desktop

webapp/src/components/CredentialsRecovery/CredentialsRecovery.js, webapp/src/components/DonationsDashboard/DonationsDashboard.js, webapp/src/components/LoginModal/Login.js, webapp/src/components/Signup/Signup.js
closes #434
- Apply lowercase, and delete spaces in this secctions
- Login
- Credential recovery
- Donations dashboard
- Run make run
- Go to login, credential recovery and donations dashboard
=> Apply lowercase, and delete spaces #434

webapp/src/routes/EditProfile/EditProfileBank.js
closes #445
- Fix problem in load url image
- Run make run
- Go to edit profile page.
=> Problem when load url image in lifebank profile page

webapp/src/components/Schedule/Schedule.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/InfoPage/InfoPageDesktop.js
closes #448 
- Apply translates in: 
- Schedule component
- Schedule view infopages
- Run make run
- Go to edit profile section or register lifebank and open schedule component, change language and review tha translations
- Go to infopages change language and review tha tranlations in schedule section
=> Apply translates

webapp/src/routes/Profile/ProfilePage.js, webapp/src/routes/Profile/ProfilePageDonor.js, webapp/src/routes/Profile/ProfilePageLifebank.js, webapp/src/routes/Profile/ProfilePageSponsor.js
closes #425 
- update donor profile design 
- update sponsor profile design 
- update lifebank profile design 
- login with a user
- go to profile section
=> Profile design

webapp/src/components/ViewSchedule/ViewSchedule.js, webapp/src/components/ViewSchedule/index.js, webapp/src/routes/InfoPage/InfoPageDesktop.js, webapp/src/routes/Profile/ProfilePageLifebank.js, webapp/src/routes/Profile/ProfilePageSponsor.js, webapp/src/theme/typography.js
closes #453 
- Create component ViewSchedule
- Apply component in this sections: 
- infopages
- profile page lifebank
- profile page sponsor
- Run make run
- Go to infopage
- Go to profile page lifebank and sponsor
=> Create schedule view component

webapp/src/components/Nearby/Nerby.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/InfoPage/InfoPageDesktop.js
closes #442 
- change empty state in nearby locations
- view nearby locations in info pages
=> Change empty state in nearby locations

webapp/src/containers/Main.js, webapp/src/routes/Home/HomeDesktop.js
closes #441 
- fix max width in big screens
=> fix max width

webapp/src/components/Carousel/Carousel.js, webapp/src/components/Logo/Logo.js, webapp/src/components/LogoUrlInput/LogoUrlInput.js, webapp/src/components/Schedule/Schedule.js, webapp/src/components/SocialMediaTextField/SocialMediaTextField.js, webapp/src/components/Telephones/Telephones.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EditProfile/EditProfile.js, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/EditProfile/EditProfileDonor.js, webapp/src/routes/EditProfile/EditProfileSponsor.js, webapp/src/routes/Profile/ProfilePageLifebank.js
closes #456
Redesign edit profile section for dondors, sponsor and lifebanks
-login with a user
-go to profile section
-edit profile
=> Redesign edit profile section

webapp/src/routes/Profile/ProfilePageSponsor.js
closes #463
- Add validations to load photos, image url and telephones.
- Run make run
- Go to profile page sponsor
=> Load data profile page sponsor is broke

webapp/src/routes/Home/Home.js
- Change varible name business type
- Run make run
- Go to filter and apply filter business type
=> fix bug apply filter

webapp/src/components/DonationsDashboard/DonationsDashboard.js, webapp/src/language/en.json, webapp/src/language/es.json
- update input placeholder
- open donation dashboard
=> Fix input placeholder

webapp/src/components/DonationsDashboard/DonationsDashboard.js
closes #467 
- fix donations dashboard button in small screens
- open donation dashboard
=> fix donations dashboard button in small screens

contracts/scripts/lifebank.sh
=> fix contracts script

webapp/src/containers/SideBar.js, webapp/src/language/en.json, webapp/src/language/es.json
=> fix(frontend): Sidebar menu elements

webapp/src/routes/InfoPage/InfoPageDesktop.js
=> fix(frontend): check image nullability

webapp/src/components/MapSelectLocation/index.js
Resolves #520 
Load current user location in the map section.
- Make run
- Go to register lifebank
- Sroll down to map location
=> fix/load current user location starting from CR

webapp/src/containers/TopBar.js
Resolves #523 
##What does this PR do?
When *Click an Option* close option menu.
=> fix(menu button): close profile options menu

webapp/src/routes/Profile/ProfilePage.js
Resolves #481 
Steps to test:
- Login to an account
- Enter the profile
=> fix(frontend): Reduce padding in profile page

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/OffersManagement/GenericOfferFormComponent.js, webapp/src/routes/OffersManagement/OffersManagement.js
=> fix(create offers): Close offer form when hitting save

webapp/src/components/Signup/SignupLifeBank.js
=> fix(webapp): fix recaptcha and button sizes

webapp/src/containers/SideBar.js
=> fix(close menu): close menu when option is click

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/NotFound/NotFound.js
=> Fix(frontend): Error 404 page

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EditProfile/EditProfile.js, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/Profile/ProfilePageDonor.js, webapp/src/routes/Profile/ProfilePageLifebank.js, webapp/src/routes/Profile/ProfilePageSponsor.js, webapp/yarn.lock
Resolves #528 
Informate the user that the changes were applied with a snackbar
Make run
Go to Lifebank, Sponsor, Donor profiles and edit the profile
Save the changes
----
---
---
=> feature(snackbar): add the snackbar alert to sponsor, lifebank and donors

hapi/src/api/account.api.js, hapi/src/api/user.api.js, hasura/metadata/tables.yaml, hasura/migrations/1614974299455_alter_table_public_user_add_column_token/down.sql, hasura/migrations/1614974299455_alter_table_public_user_add_column_token/up.sql, webapp/src/components/DonationsDashboard/DonationsDashboard.js, webapp/src/gql/account.gql.js
Resolves #497 
Add new user column and updates its value coming from a Lifebank transfer.
- Make run
- Go to Lifebank token transfer
- Trans tokens to a specific value
=> fix(webapp): add new user column and update its value

hapi/src/utils/mail.js
Resolves #509 
Show the logo in the verification email
- Make run
- Create an account
- Check your emails
=> fix(frontend): Logo broken in verification email

.github/pull_request_template.md
Resolves #
Create a PR template
- Open it in the view mode and check sections are right
=> Add .gitignore

hapi/src/api/account.api.js, hapi/src/api/lifebank.api.js, hapi/src/api/pre-register.api.js, hapi/src/routes/pre-register/pre-register-lifebank.validation.js, hapi/src/utils/lifebankcode.js, hasura/metadata/actions.graphql, hasura/metadata/tables.yaml, hasura/migrations/1616517446016_alter_table_public_preregister_lifebank_add_column_categories/down.sql, hasura/migrations/1616517446016_alter_table_public_preregister_lifebank_add_column_categories/up.sql, webapp/src/components/Signup/Signup.js, webapp/src/components/Signup/SignupLifeBank.js, webapp/src/gql/pre-register-lifebank.gql.js
Resolves #585 
Backend logic to add categories to the lifebank system
- Uncomment Front-End Connection Example at line 144, path "lifebank/webapp/src/components/Signup/SignupLifeBank.js"
-  Make run
-  Execute :add a new lifebank use case
=> feature(backend): add a new column of categories

webapp/src/components/Nearby/Nerby.js, webapp/src/gql/account.gql.js, webapp/src/gql/offer.gql.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/InfoPage/InfoPageDesktop.js
Resolves #333
Show offers by sponsor
- Make run
- More Information (Sponsor)
----
=> feature(offers view for donors): view offers by sponsor

hapi/src/api/account.api.js, hapi/src/api/lifebank.api.js, hapi/src/api/pre-register.api.js, hapi/src/routes/pre-register/pre-register-lifebank.validation.js, hapi/src/utils/lifebankcode.js, hasura/metadata/actions.graphql, hasura/metadata/tables.yaml, hasura/migrations/1616517446016_alter_table_public_preregister_lifebank_add_column_categories/down.sql, hasura/migrations/1616517446016_alter_table_public_preregister_lifebank_add_column_categories/up.sql, webapp/src/components/Signup/Signup.js, webapp/src/gql/pre-register-lifebank.gql.js
Reverts eoscostarica/lifebank#592
=> Revert "feature(backend): add a new column of categories"

hapi/src/api/account.api.js, hapi/src/api/location.api.js, hapi/src/utils/mail.js, webapp/src/components/Categories/Categories.js, webapp/src/components/Categories/index.js, webapp/src/components/Signup/SignupLifeBank.js, webapp/src/components/ViewCategories/ViewCategories.js, webapp/src/components/ViewCategories/index.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/Profile/ProfilePageLifebank.js
Resolves #584 
Show the categories when registering a lifebank 
- Make run
- Select to register a lifeband
- Search to add categories
=> fix(frontend): Add categories

webapp/src/components/Signup/Signup.js, webapp/src/components/Signup/SignupLifeBank.js
Resolves #603 
Default information for pre-register lifebank
- Make run
- Register a new lifebank
=> fix(default information): pre-register

webapp/src/components/ConsetComponent/ConsentComponent.js, webapp/src/components/Signup/Signup.js, webapp/src/components/Signup/SignupSponsor/SimpleRegisterForm.js, webapp/src/gql/account.gql.js, webapp/src/routes/EditProfile/EditProfileSponsor.js
Resolves #561 
Add name obligatory field to sponsor profile when signing up
- Sign up as sponsor
- Check that is necessary to put the sponsor name when signing up
=> feat(frontend): add sponsor obligatory name

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/EditProfile/EditProfileDonor.js, webapp/src/routes/Profile/ProfilePage.js, webapp/src/routes/Profile/ProfilePageSponsor.js
Resolves #600 
Add save profile variable query to avoid app crash when querying it
- Make run
- Sign up as Sponsor
- Confirm Email
- Login as Sponsor
- Don't accept the consent contract
- Go to profile section
- Check that app doesn't crash
=> fix(fronted): add safe profile var query to avoid app crash

webapp/src/components/Signup/SignupLifeBank.js, webapp/src/components/Signup/SignupSponsor/SimpleRegisterForm.js, webapp/src/language/en.json, webapp/src/language/es.json
Resolves #615 
Change "name" space when creating lifebank or sponsor account
- Make run
- Register a lifebank or Sponsor
=> fix(frontend): Change name

webapp/src/containers/SideBar.js
Resolves #620 
Log out is a button now
- Make run
- Log In
- Log Out
=> fix(logout button)

webapp/src/components/Signup/Signup.js
Resolves #598 
Removes email data from memory
- Make run
- Register a new user
- Try to register a new user with the same email
=> fix(email bug): remove email from memory

webapp/src/components/Signup/SignupSponsor/SimpleRegisterForm.js
Resolves #678 
Fix the sponsor Sign up process
- Make run
- Sign up as Sponsor
- Check there is no error with the signing process
=> fix(frontend): solve sponsor sign up

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/OffersApproval/OffersApproval.js, webapp/src/routes/OffersApproval/styles.js, webapp/src/theme/palette.js
Resolves #702 
Resolves #701
Handle the error when no categories are selected
- Make run
- Go to Offers Approval
=> Fix(frontend): offers bug

webapp/src/components/ConsetComponent/ConsentComponent.js, webapp/src/components/CredentialsRecovery/CredentialsRecovery.js, webapp/src/components/DonationsDashboard/DonationsDashboard.js, webapp/src/components/LoginModal/Login.js, webapp/src/components/Signup/Signup.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EditProfile/EditProfile.js, webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/Home/Home.js
Resolves #690 #636 #526
Add the same implementation for all the snackbars in the app
- Make run
- Navigate through the app
- Check if the snackbars work properly
=> Fix(snackbar): add the same format for future implementation

.github/workflows/push-dev-environment.yml, kubernetes/ingress.yaml
Resolves #748 
new ingressRoutes and env variables
=> fix(kubernetes): new ingressRoutes and env variables

hasura/migrations/1620148584870_alter_table_public_offer_add_column_icon/up.sql
Resolves #752 
Fix migrations icons
- Make run
- Step 2
- Step 3
=> fix(frontend) migrations icons

.github/workflows/push-dev-environment.yml
Resolves #
Change Secret, that secret wasn't used
=> fix(MAIL_SECRET)

kubernetes/postgres-statefulset.yaml
Resolves #759
change postgres image
=> fix(geometry)

webapp/nginx.conf
=> fix(nginx.conf)

webapp/src/routes/TermsOfUse/styles.js
Resolves #574 
Fix  Freeze header and tabs when looking at lists in mobile when scrolling
- Make run
Before
After
=> fix(frontend): fix freeze bug

.github/workflows/push-dev-environment.yml, kubernetes/ingress.yaml
=> fix: update ingress Route and remove deprecated API node

.gitignore, kubernetes/ingress.yaml
=> fix(ingress): update ssl certificates

hapi/src/api/account.api.js, hapi/src/config/i18n.config.js, hapi/src/language/en.json, hapi/src/language/es.json, hapi/src/language/index.js
Resolves #787 
Configure backend with i18next library
- Make run
=> feat(backend): configure i18n

hasura/metadata/tables.yaml, hasura/migrations/1622430708534_alter_table_public_user_add_column_receive_email/down.sql, hasura/migrations/1622430708534_alter_table_public_user_add_column_receive_email/up.sql, hasura/migrations/1622431077394_alter_table_public_user_alter_column_receive_email/down.sql, hasura/migrations/1622431077394_alter_table_public_user_alter_column_receive_email/up.sql, webapp/src/gql/account.gql.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/CancelEmailSubscription/CancelEmailSubscription.js, webapp/src/routes/CancelEmailSubscription/index.js, webapp/src/routes/CancelEmailSubscription/styles.js, webapp/src/routes/index.js
Resolves #698 
Resolves #699  
Resolves #700 
Add route to change email subscription
- Make run
- Go to http://localhost:3000/cancel-email-subscription/:account
- Click on cancel subscription
- Check email_subscription flag set to false
=> feat(frontend): add hasura mutation to change email subscription flag

hapi/src/api/account.api.js
Resolves #659 
Create the transaction history for donors
- Make run
- Go to transaction history component
=> feat(backend): add report for donor

webapp/src/routes/EditProfile/EditProfileBank.js, webapp/src/routes/EditProfile/EditProfileSponsor.js
Resolves #795 
Solve edit profile component distribution
- Make run
- Use 2K screen resolution or higher
- Go to Sponsor or Lifebank edit profile
- Check components distributions looks normal as it is shown next
=> fix(frontend): change column to row grid distribution

webapp/src/containers/SideBar.js
Resolves #652 
Fix sidebar indentation 
- Make run
- Step 2
- Step 3
=> fix(frontend): sidebar identation

webapp/src/components/OfferView/OfferView.js, webapp/src/routes/Home/HomeDesktop.js, webapp/src/routes/Home/HomeMobile.js
Resolves #791 
Remove "FAVORITE" option
- Make run
- Step 2
- Step 3
=> fix(frontend): delete favorite

.github/workflows/push-dev-environment.yml
remove ports from webapp hasura url
=> devops(webapp): update hasura URL

makefile
=> devops(webapp): update docker login

webapp/src/components/Nearby/Nerby.js, webapp/src/components/ShowElements/ShowSponsorsDesktop.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/InfoPage/InfoPageDesktop.js
Resolves #803 
Reload page when click visit page  
- Make run
- Login Sponsor
- Go to  Sponsor page
=> fix(frontend): reload page

hapi/src/api/account.api.js, hapi/src/api/user.api.js, hapi/src/cron-jobs/monthly.js
Resolves #816
Avoid to use null variable by check them before of its use
- Make run
=> refactor(backend): improve null validations

webapp/src/gql/account.gql.js
Resolves #521 
Store sign up method used by the user when registered
- Make run
- Register with lifebank method and check its result in column signup_method user table
- Register with Google/Facebook method and check its result in column signup_method user table
=> fix(backend): add  in gql query

hapi/src/api/account.api.js
Resolves #859 
When user have an inactive account, a route should appear after login try, this PR solve the problem that is causing that don't happened as expected.
- Make run
- Try to make Login with an inactive account and check you are redirected to reopen-account route
=> fix(backend): solve login reopen problem

webapp/src/components/NotificationStructure/NotificationStructure.js
Resolves #802 
Fix notification time
- Make run
- Open notifications
- See time
=> fix(frontend): fix notification time

webapp/src/routes/InfoPage/InfoPageMobile.js
Resolves #820
- Make run
- Step 2
- Step 3
=> fix(mobile): add nearby
